sudo: required
services:
  - docker

before_install: 
  - docker build -t samjamesjazz/docker-ci-cd -f Dockerfile.dev .

script:
  - docker run -e CI=true samjamesjazz/docker-ci-cd npm run test -- --coverage